#-------------------------------
# General Site Settings

menu:
- {name: 'Games', url: ''}
#- {name: 'Blog', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}
#- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Where Lucas throws all of his games!'
  rel-author: 'https://github.com/JazzyLucas'
  rel-publisher: 'https://github.com/JazzyLucas'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  # Portfolio Jekyll Theme

  This is the GitHub page where Lucas throws all of his demos for Games or software that he makes.

#-------------------------------
# Work Section

projects:
- {name: 'Tetris 3D', folder: 'tetris3D', file: 'projects/tetris3D.html'}
- {name: 'Cloud Jump', folder: 'cloudjump', file: 'projects/cloudjump.html'}
- {name: 'Voxel Vanquish', folder: 'voxelvanquish', file: 'projects/voxelvanquish.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'github', link: 'https://github.com/JazzyLucas'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
